name: clean_arch_project
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
    
  cupertino_icons: ^1.0.8
  slidy: ^4.0.4
  mobx_codegen: ^2.6.1
  flutter_modular: ^5.0.3
  mobx: ^2.3.3+2
  ft_cli: ^0.1.8+11
  dio: ^5.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true